
pool:
  vmImage: 'ubuntu-latest'


jobs:
- deployment: RenewDev
  displayName: Renew SSL on dev
  environment: 
    name: Development
    resourceType: VirtualMachine
    resourceName: websites
  strategy:
    runOnce:
      deploy:
        steps:
        - script: sudo certbot renew


- deployment: RenewProd
  displayName: Renew SSL on VM
  environment:
    name: SociallyAPI
    resourceType: VirtualMachine
    resourceName: socially-api
  strategy:
    runOnce:
      deploy:
        steps:
        - script: sudo certbot renew

