schedules:
- cron: "0 0 * * 0"
  displayName: Weekly Sunday Midnight Renewal

pool:
  vmImage: 'ubuntu-latest'


jobs:

- deployment: RenewProd
  displayName: Renew SSL on VM
  environment:
    name: SociallyAPI
    resourceType: VirtualMachine
    resourceName: socially-api
  strategy:
    runOnce:
      deploy:
        steps:
        - script: sudo certbot renew

