pool:
  vmImage: 'ubuntu-latest'


stages:
  - stage: AutomatedTests
    jobs:
      - job: UnitTests
        steps:

        # - script: dotnet test src/Socially.Server.Managers.Tests -c release
        #   displayName: Testing Managers

        - task: PublishTestResults@2
          inputs:
            testResultsFormat: XUnit
            searchFolder: src/Socially.Server.Managers.Tests
            buildConfiguration: release

      - job: IntegrationTests
        steps:

          - script: dotnet test src/Socially.WebAPI.IntegrationTests -c release
            displayName: Integration Tests


# steps:

#   - script: dotnet test src/Socially.Server.Managers.Tests -c release
#     displayName: Testing Managers

#   - script: dotnet test src/Socially.WebAPI.IntegrationTests -c release
#     displayName: Integration Tests
