pool:
  vmImage: ubuntu-latest

variables:
  unitTestOutput: $(System.DefaultWorkingDirectory)/uitests

stages:
  - stage: AutomatedTests
    jobs:
      - job: UnitTests
        steps:

          - task: DotNetCoreCLI@2
            inputs:
              command: test
              configuration: release
              workingDirectory: src/Socially.Server.Managers.Tests

      - job: IntegrationTests
        steps:

          - task: DotNetCoreCLI@2
            inputs:
              command: test
              configuration: release
              workingDirectory: src/Socially.WebAPI.IntegrationTests