pool:
  vmImage: 'ubuntu-latest'

variables:
  unitTestOutput: $(System.DefaultWorkingDirectory)/uitests

stages:
  - stage: AutomatedTests
    jobs:
      - job: UnitTests
        steps:

        - script: dotnet test src/Socially.Server.Managers.Tests -c release -l trx -r $(unitTestOutput)
          displayName: Testing Managers

        - task: PublishTestResults@2
          inputs:
            testResultsFormat: VSTest
            searchFolder: $(unitTestOutput)
            testResultsFiles: '*.trx'

      - job: IntegrationTests
        steps:

          - task: DotNetCoreCLI@2
            inputs:
              command: test
              configuration: release
              workingDirectory: src/Socially.WebAPI.IntegrationTests

          # - script: dotnet test src/Socially.WebAPI.IntegrationTests -c release
          #   displayName: Integration Tests


# steps:

#   - script: dotnet test src/Socially.Server.Managers.Tests -c release
#     displayName: Testing Managers

#   - script: dotnet test src/Socially.WebAPI.IntegrationTests -c release
#     displayName: Integration Tests
