pool:
  vmImage: ubuntu-latest

variables:
  unitTestOutput: $(System.DefaultWorkingDirectory)/uitests

stages:
  - stage: AutomatedTests
    jobs:
      - job: UnitTests
        steps:
          - template: runtest.yml
            parameters:
              path: src/Socially.Server.Managers.Tests

      - job: IntegrationTests
        steps:

          - template: runtest.yml
            parameters:
              path: src/Socially.WebAPI.IntegrationTests