pool:
  vmImage: windows-latest

variables:
  unitTestOutput: $(System.DefaultWorkingDirectory)/uitests

stages:
  - stage: AutomatedTests
    jobs:
      - job: UnitTests
        steps:
        
          - task: UseDotNet@2
            inputs:
              version: 7.0.100-rc.2.22477.23

          - script: dotnet --version

          - task: DotNetCoreCLI@2
            inputs:
              command: test
              configuration: release
              workingDirectory: src/Socially.Server.Managers.Tests

      - job: IntegrationTests
        steps:

          - task: DotNetCoreCLI@2
            inputs:
              command: test
              configuration: release
              workingDirectory: src/Socially.WebAPI.IntegrationTests