pool:
  vmImage: 'ubuntu-latest'

variables:
  unitTestOutput: $(System.DefaultWorkingDirectory)/uitests

stages:
  - stage: AutomatedTests
    jobs:
      - job: UnitTests
        steps:
        
          - task: UseDotNet@2
            inputs:
              version: 6.0.402

          - script: dotnet --version

          - task: DotNetCoreCLI@2
            inputs:
              command: test
              configuration: release
              workingDirectory: src/Socially.Server.Managers.Tests

      - job: IntegrationTests
        steps:

          - task: UseDotNet@2
            inputs:
              version: 6.0.402

          - task: DotNetCoreCLI@2
            inputs:
              command: test
              configuration: release
              workingDirectory: src/Socially.WebAPI.IntegrationTests