pool:
  vmImage: 'ubuntu-latest'

variables:
  unitTestOutput: $(System.DefaultWorkingDirectory)/uitests

stages:
  - stage: AutomatedTests
    jobs:
      - job: UnitTests
        steps:

        - script: dotnet test src/Socially.Server.Managers.Tests -l trx -r $(unitTestOutput)/ManagerResults.trx
          displayName: Testing Managers

        - task: PublishTestResults@2
          inputs:
            testResultsFormat: XUnit
            searchFolder: $(System.DefaultWorkingDirectory)/src/Socially.Server.Managers.Tests/TestResults
            testResultsFiles: '*.trx'

      - job: IntegrationTests
        steps:

          - script: dotnet test src/Socially.WebAPI.IntegrationTests -c release
            displayName: Integration Tests


# steps:

#   - script: dotnet test src/Socially.Server.Managers.Tests -c release
#     displayName: Testing Managers

#   - script: dotnet test src/Socially.WebAPI.IntegrationTests -c release
#     displayName: Integration Tests
