
pool:
  vmImage: 'ubuntu-18.04'

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - src/Socially.Core
      - src/Socially.Server.DataAccess
      - src/Socially.Server.Services
      - src/Socially.WebAPI
    

stages:
  - stage: CI
    jobs:
      - job: DotNet
        steps:
        - task: UseDotNet@2
          displayName: 'Use .NET Core sdk'
          inputs:
            packageType: sdk
            version: 5.0.100-preview.2.20176.6
            installationPath: $(Agent.ToolsDirectory)/dotnet
          
        - script: 'dotnet test src/Socially.Server.Managers.Tests -c release'
          displayName: 'Unit Test - Managers'

        - script: 'dotnet test src/Socially.WebAPI.IntegrationTests -c release'

        - task: DotNetCoreCLI@2
          inputs:
            command: 'publish'
            zipAfterPublish: true
            projects: 'src/Socially.WebAPI'
            arguments: '-o $(Build.ArtifactStagingDirectory)/Web'

        - task: PublishBuildArtifacts@1
          displayName: 'Prep for release'
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'

  - stage: Two