
pool:
  vmImage: 'ubuntu-latest'

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - src/Socially.Core
      - src/Socially.Server.DataAccess
      - src/Socially.Server.Services
      - src/Socially.WebAPI
      - pipelines/webAPI.yaml

variables:
  projectPath: src/Socially.WebAPI
  destDirectory: /var/www/socially
  projectName: Socially.WebAPI
  port: 5030


resources:
  repositories:
    - repository: templates
      type: github
      name: neville-nazerane/Common-Pipelines
      endpoint: github.com_neville-nazerane

stages:

  - stage: Build
    displayName: Compile API
    jobs:
      - job: DotnetBuild
        displayName: Building and Publishing
        steps:
          - script: |
              dotnet publish $(projectPath) -c release -o published
              tar -czvf packed.tar.gz -C published .
            displayName: Compile and Compress

          - publish: packed.tar.gz
            artifact: packed


  - stage: DeployDev
    displayName: Deploy to Dev (or try)
    jobs:
      - deployment: DevDeploy
        displayName: Deploy to Development VM
        environment:
          name: Development
          resourceType: VirtualMachine
          resourceName: websites
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    sudo ls

                    sudo rm -rf $(destDirectory)
                    sudo mkdir $(destDirectory)
                    sudo tar -xzvf packed.tar.gz -C $(destDirectory)

                    rm -rf *
                  displayName: Copying website
                  workingDirectory: $(Pipeline.Workspace)/packed
                  failOnStderr: true

                - task: DeleteFiles@1
                  displayName: Clean up

                - template: linux-service.yml
                  parameters:
                    destDirectory: $(destDirectory)
                    projectName: $(projectName)
                    port: $(port)

                    service:
                      description: Socially API
                      identifier: sociallyAPI
                      name: kestrel-socially
                                      
                    configs:
                      ASPNETCORE_ENVIRONMENT: Production
                      connectionStrings__db: $(Secrets.Db)
                      appinsights: $(Secrets.web_appInsights)
                      sendGridApiKey: $(Secrets.sendgrid)
                      blobConnString: $(Secrets.blobConnString)

                      authOptions__secret: $(Secrets.AuthSecret)
                      authOptions__audiences: website
                      authOptions__issuer: https://api.sociallyconnections.com

                      settings__clientBaseUrl: https://sociallyconnections.com
                      settings__emailFrom: accounts@sociallyconnections.com
                      settings__forgotPasswordTemplate: $(Secrets.forgotPasswordTemplate)
                      settings__imageBase: https://pics.sociallyconnections.com





            


# extends:
#   template: Shared\netcore-ubuntu.yml@templates
#   parameters:
#     useVersion: 7.x
#     projectPath: src/Socially.WebAPI
#     projectName: Socially.WebAPI
#     destDirectory: /var/www/socially
#     port: 5030

#     service:
#       description: Socially API
#       identifier: sociallyAPI
#       name: kestrel-socially

#     preBuildSteps:
#       - script: dotnet run "$(dbAdminConnectionString)"
#         workingDirectory: src/Socially.Utils.MigrationConsole

#     configs:
#       ASPNETCORE_ENVIRONMENT: Production
#       connectionStrings__db: $(Secrets.Db)
#       appinsights: $(Secrets.web_appInsights)
#       sendGridApiKey: $(Secrets.sendgrid)
#       blobConnString: $(Secrets.blobConnString)

#       authOptions__secret: $(Secrets.AuthSecret)
#       authOptions__audiences: website
#       authOptions__issuer: https://api.sociallyconnections.com

#       settings__clientBaseUrl: https://sociallyconnections.com
#       settings__emailFrom: accounts@sociallyconnections.com
#       settings__forgotPasswordTemplate: $(Secrets.forgotPasswordTemplate)
#       settings__imageBase: https://pics.sociallyconnections.com






