
pool:
  vmImage: 'ubuntu-latest'

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - src/Socially.Core
      - src/Socially.Server.DataAccess
      - src/Socially.Server.Services
      - src/Socially.WebAPI
      - pipelines/webAPI.yaml

resources:
  repositories:
    - repository: templates
      type: github
      name: neville-nazerane/Common-Pipelines
      endpoint: github.com_neville-nazerane


extends:
  template: Shared\netcore-ubuntu.yml@templates
  parameters:
    useVersion: 6.0.301
    projectPath: src/Socially.WebAPI
    projectName: Socially.WebAPI
    destDirectory: /var/www/socially
    port: 5030

    service:
      description: Socially API
      identifier: sociallyAPI
      name: kestrel-socially

    preBuildSteps:
      - script: dotnet run "$(dbAdminConnectionString)"
        workingDirectory: src/Socially.Utils.MigrationConsole

    configs:
      ASPNETCORE_ENVIRONMENT: Production
      connectionStrings__db: $(Secrets.Db)
      appinsights: $(Secrets.web_appInsights)
      sendGridApiKey: $(Secrets.sendgrid)
      blobConnString: $(Secrets.blobConnString)

      authOptions__secret: $(Secrets.AuthSecret)
      authOptions__audiences: website
      authOptions__issuer: https://api.sociallyconnections.com

      settings__clientBaseUrl: https://sociallyconnections.com
      settings__emailFrom: accounts@sociallyconnections.com
      settings__forgotPasswordTemplate: $(Secrets.forgotPasswordTemplate)
      settings__imageBase: https://pics.sociallyconnections.com






