
pool:
  vmImage: 'ubuntu-latest'

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - src/Socially.Core
      - src/Socially.Apps.Consumer
      - src/Socially.Website
      - pipelines/website.yaml

variables:
  projectPath: src/Socially.Website
  projectName: Socially.Website

stages:

  - stage: Build
    jobs:
      - job: Building
        steps:

          - script: |
              dotnet publish $(projectPath) -c release -o published

          - publish: published
            artifact: packed

  # - stage: Deploy
  #   jobs:
  #     - job: Deploying
  #       steps:
          
          

# resources:
#   repositories:
#     - repository: templates
#       type: github
#       name: neville-nazerane/Common-Pipelines
#       endpoint: github.com_neville-nazerane


# extends:
#   template: Shared\netcore-ubuntu.yml@templates
#   parameters:
#     useVersion: 7.x
#     projectPath: src/Socially.Website
#     projectName: Socially.Website
#     destDirectory: /var/www/sociallySite
#     port: 5075

#     service:
#       description: Socially Website
#       identifier: sociallySite
#       name: kestrel-sociallySite
#     configs:
#       ASPNETCORE_ENVIRONMENT: Development
    
