
pool:
  vmImage: 'ubuntu-latest'

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - src/Socially.Core
      - src/Socially.Apps.Consumer
      - src/Socially.Website
      - src/Socially.Utils.SimpleAzCopy
      - pipelines/website.yaml

variables:
  projectPath: src/Socially.Website
  projectName: Socially.Website
  azCopyPath: src/Socially.Utils.SimpleAzCopy

stages:

  - stage: Build
    jobs:
      - job: Building
        steps:

          - script: |
              dotnet publish $(projectPath) -c release -o published
              # mkdir publishes
              # tar -czvf publishes/packed.tar.gz -C published .
            displayName: building blazor

          - publish: published
            artifact: packed

  - stage: Deploy
    jobs:
      - job: Deploying

        steps:

        - download: current

        - script: 
            dotnet run "$(webBlobConnString)" '$web' $(Pipeline.Workspace)/packed/wwwroot
          displayName: Dotnet AZ Deploy
          workingDirectory: $(azCopyPath)

        - task: AzureCLI@2
          inputs:
            azureSubscription: socially
            scriptType: pscore
            scriptLocation: inlineScript
            inlineScript: az cdn endpoint purge -g Socially -n sociallycdn --profile-name sociallywebsiteCDN --content-paths '/*'

        # - script: tree
        #   displayName: show em all
        #   workingDirectory: $(Pipeline.Workspace)/packed 
        
        # - task: AzureFileCopy@4
        #   inputs:
        #     SourcePath: '$(Pipeline.Workspace)/packed/wwwroot'
        #     azureSubscription: 'socially'
        #     Destination: AzureBlob
        #     storage: 'sociallyimages'
        #     ContainerName: '$web'
        #     CleanTargetBeforeCopy: true

        


            
          
          

# resources:
#   repositories:
#     - repository: templates
#       type: github
#       name: neville-nazerane/Common-Pipelines
#       endpoint: github.com_neville-nazerane


# extends:
#   template: Shared\netcore-ubuntu.yml@templates
#   parameters:
#     useVersion: 7.x
#     projectPath: src/Socially.Website
#     projectName: Socially.Website
#     destDirectory: /var/www/sociallySite
#     port: 5075

#     service:
#       description: Socially Website
#       identifier: sociallySite
#       name: kestrel-sociallySite
#     configs:
#       ASPNETCORE_ENVIRONMENT: Development
    
