
pool:
  vmImage: ubuntu-latest

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - src/Socially.Core
      - src/Socially.Apps.Consumer
      - src/Socially.Website
      - src/Socially.Utils.SimpleAzCopy
      - pipelines/website.yaml

variables:
  projectPath: src/Socially.Website
  projectName: Socially.Website
  azCopyPath: src/Socially.Utils.SimpleAzCopy

stages:

  - stage: Build
    jobs:
      - job: Building
        steps:

          - script: |
              dotnet publish $(projectPath) -c release -o published
              # mkdir publishes
              # tar -czvf publishes/packed.tar.gz -C published .
            displayName: building blazor

          - publish: published
            artifact: packed

  - stage: Deploy
    jobs:
      - job: Deploying

        steps:

        - download: current
          displayName: Download artifacts

        - script: 
            dotnet run "$(webBlobConnString)" '$web' $(Pipeline.Workspace)/packed/wwwroot
          displayName: Dotnet AZ Deploy
          workingDirectory: $(azCopyPath)

        - task: AzureCLI@2
          displayName: Purge CDN
          inputs:
            azureSubscription: socially
            scriptType: pscore
            scriptLocation: inlineScript
            inlineScript: az cdn endpoint purge -g Socially -n sociallycdn --profile-name sociallywebsiteCDN --content-paths '/*'
