
pool:
  vmImage: 'windows-latest'

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - src/Socially.Core
      - src/Socially.Apps.Consumer
      - src/Socially.Website
      - pipelines/website.yaml

variables:
  projectPath: src/Socially.Website
  projectName: Socially.Website

stages:

  - stage: Build
    jobs:
      - job: Building
        pool:
          vmImage: 'ubuntu-latest'
        steps:

          - script: |
              dotnet publish $(projectPath) -c release -o published
              mkdir publishes
              tar -czvf publishes/packed.tar.gz -C published .
            displayName: building blazor

          - publish: publishes
            artifact: packed

  - stage: Deploy
    jobs:
      - job: Deploying
        pool:
          vmImage: 'windows-latest'

        steps:

        - download: packed

        - script: tree
          displayName: show em all
          workingDirectory: $(Pipeline.Workspace)/packed 
        
        - task: AzureFileCopy@4
          condition: false
          inputs:
            SourcePath: '$(Pipeline.Workspace)/packed'
            azureSubscription: 'socially'
            Destination: AzureBlob
            storage: 'sociallyimages'
            ContainerName: '$web'
            CleanTargetBeforeCopy: true

        


            
          
          

# resources:
#   repositories:
#     - repository: templates
#       type: github
#       name: neville-nazerane/Common-Pipelines
#       endpoint: github.com_neville-nazerane


# extends:
#   template: Shared\netcore-ubuntu.yml@templates
#   parameters:
#     useVersion: 7.x
#     projectPath: src/Socially.Website
#     projectName: Socially.Website
#     destDirectory: /var/www/sociallySite
#     port: 5075

#     service:
#       description: Socially Website
#       identifier: sociallySite
#       name: kestrel-sociallySite
#     configs:
#       ASPNETCORE_ENVIRONMENT: Development
    
